# -*- coding: utf-8 -*-
"""Exemplos_Python_basico

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LBABG8VTqkhZxODGC1wpnpy9kQkJSRMp
"""

#1.Faça um Programa que mostra a mensagem "Alô mundo" na tela.
print("Alô mundo")

#2.Faça um Programa que peça um número e então mostre a mensagem O número informado foi [número].
numero = float(input("Digite um número: "))
print("O numero digitado foi:", numero)

#3.Faça um Programa que peça dois números e imprima a soma
numero1 = float(input("Digite o primeiro número: "))
numero2 = float(input("Digite o segundo número: "))
soma = numero1 + numero2
print("A soma dos números é:",soma)

#4-Faça um Programa que peça as 4 notas bimestrais e mostre a média.
nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
nota3 = float(input("Digite a terceira nota: "))
nota4 = float(input("Digite a quarta nota: "))
media = (nota1 + nota2 + nota3 + nota4) / 4
print("A média das notas é:",media)

#5. Faça um Programa que converte metros para centímetros.
metros = float(input("Digite a medida em metros: "))
centimetros = metros * 100
print(f"{metros} metros equivalem a {centimetros} centímetros.")

#6. Faça um Programa que parte o raio de um círculo, calcule e mostre sua área.
import math
raio = float(input("Digite o raio do círculo: "))
area = math.pi * (raio ** 2)
print("A área do círculo é:",area)

#7. Faça um programa que calcula a área de um quadrado, em seguida mostre o dobro desta área para o usuário.
lado = float(input("Digite o comprimento do lado do quadrado: "))
area = lado ** 2
dobro_area = 2 * area
print("A área do quadrado é:", area)
print("O dobro da área é:",dobro_area)

#8. Faça um Programa que pergunta quanto você ganha por hora e o número de horas trabalhadas no mês.
#Calcule e mostre o total do seu salário no referido mês.
valor_por_hora = float(input("Digite quanto você ganha por hora: "))
horas_trabalhadas = float(input("Digite o número de horas trabalhadas no mês: "))
salario = valor_por_hora * horas_trabalhadas
print(f"Seu salário no referido mês é: R${salario:.2f}")

#9. Faça um Programa que parte a temperatura em graus Farenheit, transforma e mostra a temperatura em graus Celsius. C=(5*(F-32)/9).
fahrenheit = float(input("Digite a temperatura em graus Fahrenheit: "))
celsius = (5 * (fahrenheit - 32)) / 9
print(f"A temperatura em graus Celsius é: {celsius:.2f}°C")

#10. Faça um programa que parte a temperatura em graus Celsius, transforma e mostra em graus Farenheit.
celsius = float(input("Digite a temperatura em graus Celsius: "))
fahrenheit = (celsius * 9/5) + 32
print(f"A temperatura em graus Fahrenheit é: {fahrenheit:.2f}°F")
















'''12. Tendo como dados de entrada a altura de uma pessoa, construa um algoritmo
que calcula seu peso ideal, usando a seguinte fórmula: (72.7*altura) - 58
13. Tendo como dado de entrada a altura (h) de uma pessoa, construa um algoritmo
que calcule seu peso ideal, utilizando as seguintes fórmulas:
● Para homens: (72,7*h) - 58
● Para mulheres: (62,1*h) - 44,7
14. João Papo-de-Pescador, homem de bem, comprou um microcomputador para
controlar o rendimento diário de seu trabalho. Toda vez que ele trouxer um peso de
peixes maior que o previsto pelo regulamento de pesca do estado de São Paulo (50
quilos) deverá pagar uma multa de R$ 4,00 por quilo excedente. João precisa que
você faça um programa que leia a variável peso (peso de peixes) e calcule o
excesso. Gravar na variável excesso a quantidade de quilos além do limite e na
multa variável o valor da multa que João deverá pagar. Imprima os dados do
programa com as mensagens apropriadas.
15. Faça um Programa que pergunte quanto você ganha por hora e o número de
horas trabalhadas no mês. Calcule e mostre o total do seu salário no mês
específico, sabendo-se que são descontados 11% para o Imposto de Renda, 8%
para o INSS e 5% para o sindicato, faça um programa que nos dê:
● salário bruto.
● quanto pagou ao INSS.
● quanto pagou ao sindicato.
● o salário líquido.
calcule os descontos e o salário líquido, conforme tabela abaixo:
● Salário Bruto: R$
● IR (11%): R$
● INSS (8%): R$
● Sindicato (5%): R$
● Salário Líquido: R$
Obs.: Salário Bruto - Descontos = Salário Líquido.
16. Faça um programa para uma loja de tintas. O programa deverá pedir o tamanho
em metros quadrados da área a ser pintada. Considere que a cobertura de tinta é
de 1 litro para cada 3 metros quadrados e que a tinta é vendida em latas de 18
litros, que custa R$ 80,00. Informe ao usuário as quantidades de latas de tinta que
serão compradas e o preço total.
17. Faça um Programa para uma loja de tintas. O programa deverá pedir o tamanho
em metros quadrados da área a ser pintada. Considere que a cobertura de tinta é
de 1 litro para cada 6 metros quadrados e que a tinta é vendida em latas de 18
litros, que custa R$ 80,00 ou em galões de 3,6 litros, que custa R$ 25,00 .
● Informe ao usuário as quantidades de tinta a serem compradas e os preços
relevantes em 3 situações:
● comprar apenas latas de 18 litros;
● comprar apenas galões de 3,6 litros;
● Ajuste latas e galões, de forma que o preço seja o menor. Adicione 10% de
folga e sempre arredonde os valores para cima, isto é, considere latas
cheias.
18. Faça um programa que peça o tamanho de um arquivo para download (em MB)
e a velocidade de um link de Internet (em Mbps), calcule e informe o tempo
aproximado de download do arquivo usando este link (em minutos).