# -*- coding: utf-8 -*-
"""ExercíciosEstrutura de Repetição - FOR

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14BxW1PLbm6G5mv7vu9T97riGYb-XPbkN
"""



#ExercíciosEstrutura de Repetição - FOR
#1-Faça um programa que receba um número e que calcule e mostre a tabuada desse número.
numero = int(input("Digite um número: "))
for i in range(1, 11):
    print(f"{numero} x {i} = {numero * i}")

#2-Faça um programa que verifique e mostre os números entre 1.000 e 2.000 (inclusive) que, quando divididos por 5 produzam resto igual a 2.
print("Números entre 1000 e 2000 que divididos por 5 têm resto 2:")
for num in range(1000, 2001):
    if num % 5 == 2:
        print(num)

#3-Uma loja tem tem uma política de descontos de acordo com o valor da compra do cliente.Os descontos começam acima dos R$500A cada 100 reais  acima dos R$500,00 o cliente ganha 1% de desconto cumulativo até 25%. Por exemplo: R$500 = 1% || R$600,00 = 2% ... etc...
#Faça um programa que exiba essa tabela de descontos no seguinte formato: Valor dacompra -porcentagem de desconto -valor final
v_compra = 500
while v_compra <= 1000:
    desconto = (_compra - 500) / 100
    print(f"{v_compra} - {desconto}% - {v_compra * (1 - desconto / 100)}")
    v_compra += 100

#4-Faça um programa que receba a idade de 15 pessoas e que calcule e mostre: A quantidade  de  pessoas  em  cada  faixa  etária;
#A  percentagem  de  pessoas  na primeira e na última faixa etária, com relação ao total de pessoas.plaintextfaixa1=Até15anosfaixa2=De16a30anosfaixa3=De31a45anosfaixa4=De46a60anosfaixa5=Acimade61anos
faixa1 = faixa2 = faixa3 = faixa4 = faixa5 = 0
for _ in range(15):
    idade = int(input("Digite a idade: "))
    if idade <= 15:
        faixa1 += 1
    elif 16 <= idade <= 30:
        faixa2 += 1
    elif 31 <= idade <= 45:
        faixa3 += 1
    elif 46 <= idade <= 60:
        faixa4 += 1
    else:
        faixa5 += 1

total_pessoas = faixa1 + faixa5
percent_faixa1 = (faixa1 / total_pessoas) * 100
percent_faixa5 = (faixa5 / total_pessoas) * 100

print(f"Faixa 1: {faixa1} pessoas")
print(f"Faixa 2: {faixa2} pessoas")
print(f"Faixa 3: {faixa3} pessoas")
print(f"Faixa 4: {faixa4} pessoas")
print(f"Faixa 5: {faixa5} pessoas")
print(f"Porcentagem na faixa 1: {percent_faixa1}%")
print(f"Porcentagem na faixa 5: {percent_faixa5}%")


#5-Faça um programa que mostre todos os primos entre 1 e N sendo N um número inteiro fornecido pelo usuário.
# O programa deverá  mostrar  também  o número de divisões que ele executou para encontrar os números primos. Serão avaliados o funcionamento, o estilo e o número de testes (divisões) executados.
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

N = int(input("Digite um número inteiro: "))
count = 0
for i in range(2, N+1):
    if is_prime(i):
        count += 1
        print(i)
print(f"Número de divisões: {count}")


#6-Faça  um  programa  que  peça  para  n  pessoas  a  sua  idade,  ao  final  o  programa devera verificar se a média de idade da turma varia entre 0 e 25,26 e 60 e maior  que  60; e então,  dizer  se  a  turma  é  jovem,
#adulta ou  idosa,  conforme  a média calculada.
n = int(input("Digite o número de pessoas: "))
idades = []
for _ in range(n):
    idade = int(input("Digite a idade: "))
    idades.append(idade)

media = sum(idades) / n
if 0 < media <= 25:
    print("Turma jovem")
elif 26 <= media <= 60:
    print("Turma adulta")
else:
    print("Turma idosa")


#7-Numa  eleição  existem  três  candidatos.  Faça um programa que  peça  o  número total de eleitores. Peça para cada eleitor votar e ao final mostrar o número de votos de cada candidato.
votos_candidato1 = votos_candidato2 = votos_candidato3 = 0
total_eleitores = int(input("Digite o número total de eleitores: "))
for _ in range(total_eleitores):
    voto = int(input("Digite o número do candidato (1, 2 ou 3): "))
    if voto == 1:
        votos_candidato1 += 1
    elif voto == 2:
        votos_candidato2 += 1
    elif voto == 3:
        votos_candidato3 += 1

print(f"Votos do candidato 1: {votos_candidato1}")
print(f"Votos do candidato 2: {votos_candidato2}")
print(f"Votos do candidato 3: {votos_candidato3}")


#8-Faça um programa que calcule o número médio de alunos por turma. Para isto, peça  a  quantidade  de  turmas  e  a  quantidade  de  alunos  para  cada  turma.  As turmas não podem ter mais de 40 alunos.
num_turmas = int(input("Digite a quantidade de turmas: "))
total_alunos = 0
for i in range(1, num_turmas + 1):
    alunos = int(input(f"Digite a quantidade de alunos na turma {i}: "))
    while alunos > 40:
        alunos = int(input("O número de alunos não pode ser superior a 40. Digite novamente: "))
    total_alunos += alunos

media_alunos = total_alunos / num_turmas
print(f"O número médio de alunos por turma é {media_alunos}.")


#9-Faça um programa que calcule o valor total investido por um colecionador em sua  coleção  de  CDs  e  o  valor  médio  gasto  em  cada  um  deles.  O  usuário  deverá informar a quantidade de CDs e o valor para em cada um.
num_cds = int(input("Digite a quantidade de CDs: "))
valor_total = 0
for i in range(1, num_cds + 1):
    valor_cd = float(input(f"Digite o valor do CD {i}: "))
    valor_total += valor_cd

valor_medio = valor_total / num_cds
print(f"O valor total investido foi de {valor_total} e o valor médio gasto foi de {valor_medio}.")


#10-Faça  um  programa  que  imprima  na  tela  os  números  de  1  a  20,  um  abaixo  do outro.Depois modifique o programa para que ele mostre os números um ao lado do outro
# Impressão um abaixo do outro
for i in range(1, 21):
    print(i)

# Impressão um ao lado do outro
for i in range(1, 21):
    print(i, end=" ")