# -*- coding: utf-8 -*-
"""Listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10FbUdhAqRxnRMQG4mgW5dzB7hvVhjGL9
"""

#Listas
#Declare uma lista de 10 posições e o preencha com os 10 primeiros números impares e o escreva.
lista_impares = [2 * i + 1 for i in range(10)]
print("Lista dos primeiros 10 números ímpares:", lista_impares)

#Declare uma lista de 16 posições e troque os 8 primeiros valores pelos 8 últimos e vice-e-versa. Escreva ao final o vetor obtido.
lista_troca = list(range(16))
lista_troca[:8], lista_troca[8:] = lista_troca[8:], lista_troca[:8]
print("Lista após a troca:", lista_troca)

#Declare uma lista de 40 posições e atribua valor 0 para todos os elementos que possuírem valores negativos.
lista_valores = [i if i >= 0 else 0 for i in range(-20, 20)]
print("Lista com valores negativos substituídos por 0:", lista_valores)

#Declare duas listas de 4 posições. Verifique e escreva se um é anagrama de outro. Ex: ARARA - ARARA - são anagramas
def sao_anagramas(lista1, lista2):
    return sorted(lista1) == sorted(lista2)

lista1 = ['A', 'R', 'A', 'R']
lista2 = ['A', 'R', 'A', 'A']

if sao_anagramas(lista1, lista2):
    print("As listas são anagramas.")
else:
    print("As listas não são anagramas.")