# -*- coding: utf-8 -*-
"""While.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10FbUdhAqRxnRMQG4mgW5dzB7hvVhjGL9
"""

#While
#Uma loja deseja cadastrar 5 clientes e verificar se o faturamento da loja foi superior a loja B (faturamento = 54000). se o faturamento atingir esse valor mostre na tela uma mensagem contendo em quanto foi superado o faturamento.
faturamento_loja = 0
numero_clientes = 0
faturamento_loja_b = 54000

while numero_clientes < 5:
    valor_compra = float(input(f"Digite o faturamento do cliente {numero_clientes + 1}: "))
    faturamento_loja += valor_compra
    numero_clientes += 1

if faturamento_loja > faturamento_loja_b:
    diferenca = faturamento_loja - faturamento_loja_b
    print(f"O faturamento foi superior à loja B por R${diferenca:.2f}.")

#Uma companhia de teatro deseja dar uma série de espetáculos. Fatos:
#A direção calcula que praticando o preço de R$5,00 serão vendidos 120 ingressos
#As despesas são fixas em R$ 200,00.
#Ao diminuir R$ 0,50 o preço dos ingressos espera-se que as vendas aumentem em 26 ingressos.
preco_padrao = 5.00
vendas_padrao = 120
despesas_fixas = 200.00
aumento_vendas = 26
reducao_preco = 0.50

vendas = vendas_padrao
preco_atual = preco_padrao

while preco_atual - reducao_preco >= 0:
    faturamento = vendas * preco_atual - despesas_fixas
    print(f"Preço do ingresso: R${preco_atual:.2f} - Faturamento: R${faturamento:.2f}")
    vendas += aumento_vendas
    preco_atual -= reducao_preco

#Faça um programa que receba a idade de dez pessoas e que calcule e mostre a quantidade de pessoas com idade maior ou igual a 18 anos.
contador = 0
indice = 1

while indice <= 10:
    idade = int(input(f"Digite a idade da pessoa {indice}: "))
    if idade >= 18:
        contador += 1
    indice += 1

print(f"A quantidade de pessoas com 18 anos ou mais é: {contador}")

#Faça um programa que receba a idade, altura e o peso de 25 pessoas, Calcule e mostre:
#A quantidade de pessoas com idade superior a 50 anos;
#A média das Alturas das pessoas com idade entre 10 e 20 anos
#A porcentagem das pessoas com peso inferior a 40 quilos entre todas as pessoas analisadas.
contador_idade_superior_50 = 0
soma_alturas_10_20 = 0
contador_peso_inferior_40 = 0
total_pessoas = 25
indice = 0

while indice < total_pessoas:
    idade = int(input(f"Digite a idade da pessoa {indice + 1}: "))
    altura = float(input(f"Digite a altura da pessoa {indice + 1}: "))
    peso = float(input(f"Digite o peso da pessoa {indice + 1}: "))

    if idade > 50:
        contador_idade_superior_50 += 1

    if 10 <= idade <= 20:
        soma_alturas_10_20 += altura

    if peso < 40:
        contador_peso_inferior_40 += 1

    indice += 1

media_alturas_10_20 = soma_alturas_10_20 / total_pessoas
porcentagem_peso_inferior_40 = (contador_peso_inferior_40 / total_pessoas) * 100

print(f"A quantidade de pessoas com idade superior a 50 anos é: {contador_idade_superior_50}")
print(f"A média das alturas das pessoas entre 10 e 20 anos é: {media_alturas_10_20:.2f}")
print(f"A porcentagem das pessoas com peso inferior a 40 quilos é: {porcentagem_peso_inferior_40:.2f}%")



#Faça um programa que receba a idade e o peso de sete pessoas. Calcule e mostre:
#A quantidade de pessoas com mais de 90 quilos;
#A média das idades das sete pessoas;
contador_mais_de_90 = 0
soma_idades = 0
total_pessoas = 7
indice = 0

while indice < total_pessoas:
    idade = int(input(f"Digite a idade da pessoa {indice + 1}: "))
    peso = float(input(f"Digite o peso da pessoa {indice + 1}: "))

    if peso > 90:
        contador_mais_de_90 += 1

    soma_idades += idade
    indice += 1

media_idades = soma_idades / total_pessoas

print(f"A quantidade de pessoas com mais de 90 quilos é: {contador_mais_de_90}")
print(f"A média das idades das sete pessoas é: {media_idades:.2f}")